# Generated by Django 5.1.7 on 2025-04-24 02:24

import images.services.image_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_delete_imagecollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='url',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to=images.services.image_service.userImagesDirPath),
        ),
    ]
