# Generated by Django 5.1.7 on 2025-04-30 01:24

import django.db.models.deletion
import images.services.image_service
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_imagemodel_url_imagemodel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DitheredImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=images.services.image_service.userImagesDirPath)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
