# Generated by Django 5.1.7 on 2025-05-31 06:17

import django.db.models.deletion
import images.services.image_service
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_ditheredimagemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ditheredimagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to=images.services.image_service.ditheredImagesDirPath),
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('device_model', models.CharField(choices=[('7in3e', '7.3inch E-Paper'), ('4in0e', '4inch E-Paper'), ('13in3e', '13.3inch E-Paper')])),
                ('images', models.ManyToManyField(to='images.imagemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
