# Generated by Django 5.1.7 on 2025-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_ditheredimagemodel_image_imagecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='device_model',
            field=models.IntegerField(choices=[(1, 'Epd4In0'), (2, 'Epd7In3'), (3, 'Epd13In3')]),
        ),
    ]
