# Generated by Django 5.1.7 on 2025-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_imagecollection_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecollection',
            name='dithered_images',
            field=models.ManyToManyField(to='images.ditheredimagemodel'),
        ),
    ]
