# Generated by Django 5.1.7 on 2025-06-13 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_imagecollection_dithered_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='device_model',
            field=models.IntegerField(choices=[(0, 'Epd4In0'), (1, 'Epd7In3'), (2, 'Epd13In3')]),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='name',
            field=models.CharField(max_length=36),
        ),
        migrations.CreateModel(
            name='DisplayDeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('serial_id', models.CharField(max_length=16)),
                ('device_model', models.IntegerField(choices=[(0, 'Epd4In0'), (1, 'Epd7In3'), (2, 'Epd13In3')], null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.imagecollection')),
            ],
        ),
    ]
