# Generated by Django 5.1.7 on 2025-10-05 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_raspberrypi_pairing_code'),
        ('images', '0009_displaydeviceconfig_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.imagecollection'),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='device_model',
            field=models.IntegerField(choices=[(0, 'Epd4In0'), (1, 'Epd7In3'), (2, 'Epd13In3')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
