# Generated by Django 5.1.7 on 2025-10-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_raspberrypi_collection_raspberrypi_device_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='display_name',
            field=models.CharField(default='Default name', max_length=100),
            preserve_default=False,
        ),
    ]
